[tool.poetry]
name = "pentest154"
version = "0.1.0"
description = ""
authors = ["Alexeev Bronislav <bro.alexeev@inbox.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
rich = "^13.8.0"
ruff = "^0.6.4"
python-whois = "^0.9.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
